
ex1_burgers:
  lambda: null
  node_feats: 1
  edge_feats: 1
  pos_dim: 1
  n_targets: 1
  n_hidden: 96
  num_feat_layers: 0
  num_ft_layers: 4
  n_head: 1
  pred_len: 0
  n_freq_targets: 0
  dim_feedforward: 192
  feat_extract_type: null
  attention_type: fourier
  xavier_init: 0.001
  diagonal_weight: 0.01
  symmetric_init: False
  layer_norm: False
  attn_norm: True
  batch_norm: False
  spacial_residual: False
  return_attn_weight: False
  return_ortho: False
  residual_type: plus
  seq_len: null
  bulk_regression: False
  decoder_type: ifft
  freq_dim: 48
  num_regressor_layers: 2
  fourier_modes: 16
  spacial_dim: 1
  spacial_fc: False
  dropout: 0.0
  encoder_dropout: 0.0
  decoder_dropout: 0.0
  debug: False
